version: '3.8'
services:
  backend:
    container_name: flask-microservice-1
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: 'nodemon --exec python main.py'
    ports:
      - 8002:5000
    volumes:
      - .:/app
    depends_on: 
      - database

  queue:
    container_name: flask-microservice-queue-1
    build:
      context: .
      dockerfile: Dockerfile
    command: 'nodemon --exec python consumer.py'
    volumes:
      - .:/app
    depends_on:
      - database
  
  database:
    image: mysql:8.0.21
    restart: unless-stopped
    container_name: flask-microservice-1-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 33067:3306
