version: '3.8'
services:
  backend:
    container_name: django-microservice-1
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: 'nodemon --exec python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8001:8000
    volumes:
      - .:/app
    depends_on: 
      - database
  
  queue:
    container_name: django-microservice-queue-1
    build:
      context: .
      dockerfile: Dockerfile
    command: 'nodemon --exec python consumer.py'
    volumes:
      - .:/app
    depends_on:
      - database

  database:
    image: mysql:8.0.21
    restart: unless-stopped
    container_name: django-microservice-database-1
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 33066:3306
